version: "3.8"

networks:
  knight-shift-network:
    name: knight-shift-network
    driver: bridge

volumes:
  postgres_data:


services:
  application:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 18-bullseye
        USER_UID: 1000
        USER_GID: 1000
    networks:
      - knight-shift-network
    volumes:
      - ..:/workspace:cached
      - ~/.ssh:/home/node/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    user: node
    env_file:
      - ./workspace.env
    ports:
      - 3000:3000
      - 5432:5432
      - 8080:8080

  postgres:
    container_name: postgres
    image: postgres:15.1
    restart: always
    network_mode: service:application
    env_file:
      - ./postgres.env
    volumes:
      - ./init-postgres.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    container_name: redis
    image: redis:latest
    network_mode: service:application
